name: OGD Website - Webpage Test Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}

env:
  DEPLOY_HOST: ${{ vars.OGD_STAGING_HOST }}
  DEPLOY_DIR:          ${{ vars.WSGI_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}
  DEPLOY_URL:  ${{ vars.OGD_STAGING_HOST }}/${{ vars.WSGI_WEB_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      custom_deploy_url:
        description: "The base URL at which the website is deployed"
        required: true
        default: "https://opengamedata.fielddaylab.wisc.edu"
  workflow_call:
  
jobs:
  webpage_tests:
    name: cURL Test of Webpages
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:

  # 1. Local checkout & config
    - name: Announce Run
      run: echo "Testing ${{ github.repository }} deployed at ${{ inputs.deploy_url || env.DEPLOY_URL }}"
    
  # 2. Build 

  # 3. Remote config & execute
    - name: Test Main Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/index.html
    - name: Test "About Us" Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/about.html
    - name: Test "Get Involved" Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/getinvolved.html
    - name: Test AQUALAB Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=AQUALAB
    - name: Test BACTERIA Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=BACTERIA
    - name: Test BALLOON Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=BALLOON
    - name: Test BLOOM Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=BLOOM
    - name: Test CRYSTAL Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=CRYSTAL
    - name: Test CYCLE_CARBON Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=CYCLE_CARBON
    - name: Test CYCLE_NITROGEN Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=CYCLE_NITROGEN
    - name: Test CYCLE_WATER Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=CYCLE_WATER
    - name: Test EARTHQUAKE Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=EARTHQUAKE
    - name: Test ICECUBE Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=ICECUBE
    - name: Test JOURNALISM Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=JOURNALISM
    - name: Test JOWILDER Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=JOWILDER
    - name: Test LAKELAND Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=LAKELAND
    - name: Test MAGNET Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=MAGNET
    - name: Test PENGUINS Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=PENGUINS
    - name: Test SHADOWSPECT Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=SHADOWSPECT
    - name: Test SHIPWRECKS Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=SHIPWRECKS
    - name: Test THERMOVR Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=THERMOVR
    - name: Test TRANSFORMATION_QUEST Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=TRANSFORMATION_QUEST
    - name: Test WAVES Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=WAVES
    - name: Test WEATHER_STATION Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=WEATHER_STATION
    - name: Test WIND Page
      run: curl -Is --fail-with-body ${{ inputs.custom_deploy_url || env.DEPLOY_URL }}/gamedata.html?game=WIND

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: ./*.log
